env: "local"
http_server:
  host: "localhost"
  port: "50056"
log_config:
  log_level: "debug"
  log_format: "json"
  log_output: "stdout"
user-service:
  host: "localhost"
  port: "50052"
sso-service:
  host: "localhost"
  port: "50051"
authz-service:
  host: "localhost"
  port: "50054"
order-service:
  host: "localhost"
  port: "50058"
banking-service:
  host: "localhost"
  port: "50057"
wallet-service:
  host: "localhost"
  port: "3000"
swagger_config:
  host: "localhost"
  port: "8080"
  base_path: "/api/v1"
  schemes: "http"